# Generated by Django 6.1 on 2026-08-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condition_list',
            options={'ordering': ['Condition'], 'verbose_name': 'Состояния', 'verbose_name_plural': 'Состояния'},
        ),
        migrations.AlterModelOptions(
            name='full_name_of_the_performer_list',
            options={'ordering': ['Full_name_of_the_performer'], 'verbose_name': 'Исполнители', 'verbose_name_plural': 'Исполнители'},
        ),
        migrations.AlterModelOptions(
            name='historicalcondition_list',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Состояния', 'verbose_name_plural': 'historical Состояния'},
        ),
        migrations.AlterModelOptions(
            name='historicalfull_name_of_the_performer_list',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Исполнители', 'verbose_name_plural': 'historical Исполнители'},
        ),
        migrations.AlterModelOptions(
            name='historicalrequest',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Заявки', 'verbose_name_plural': 'historical Заявки'},
        ),
        migrations.AlterModelOptions(
            name='historicaltype_of_work_list',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Виды работ', 'verbose_name_plural': 'historical Виды работ'},
        ),
        migrations.AlterModelOptions(
            name='type_of_work_list',
            options={'ordering': ['Type_of_work'], 'verbose_name': 'Виды работ', 'verbose_name_plural': 'Виды работ'},
        ),
        migrations.AlterField(
            model_name='condition_list',
            name='Condition',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='full_name_of_the_performer_list',
            name='Full_name_of_the_performer',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Ф.И.О. исполнителя'),
        ),
        migrations.AlterField(
            model_name='historicalcondition_list',
            name='Condition',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='historicalcondition_list',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfull_name_of_the_performer_list',
            name='Full_name_of_the_performer',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Ф.И.О. исполнителя'),
        ),
        migrations.AlterField(
            model_name='historicalfull_name_of_the_performer_list',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalrequest',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltype_of_work_list',
            name='Type_of_work',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Вид работ'),
        ),
        migrations.AlterField(
            model_name='historicaltype_of_work_list',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='Files',
            field=models.FileField(blank=True, upload_to='./static/files/%Y/%m/%d/', verbose_name='Загрузка файла'),
        ),
        migrations.AlterField(
            model_name='type_of_work_list',
            name='Type_of_work',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Вид работ'),
        ),
    ]
