# Generated by Django 6.1 on 2026-09-17 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_alter_condition_list_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condition_list',
            options={'ordering': ['Condition'], 'verbose_name': 'Conditions', 'verbose_name_plural': 'Conditions'},
        ),
        migrations.AlterModelOptions(
            name='full_name_of_the_performer_list',
            options={'ordering': ['Full_name_of_the_performer'], 'verbose_name': 'Performers', 'verbose_name_plural': 'Performers'},
        ),
        migrations.AlterModelOptions(
            name='historicalcondition_list',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Conditions', 'verbose_name_plural': 'historical Conditions'},
        ),
        migrations.AlterModelOptions(
            name='historicalfull_name_of_the_performer_list',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Performers', 'verbose_name_plural': 'historical Performers'},
        ),
        migrations.AlterModelOptions(
            name='historicalrequest',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Requests', 'verbose_name_plural': 'historical Requests'},
        ),
        migrations.AlterModelOptions(
            name='historicaltype_of_work_list',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Types of work', 'verbose_name_plural': 'historical Types of work'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-pk'], 'verbose_name': 'Requests', 'verbose_name_plural': 'Requests'},
        ),
        migrations.AlterModelOptions(
            name='type_of_work_list',
            options={'ordering': ['Type_of_work'], 'verbose_name': 'Types of work', 'verbose_name_plural': 'Types of work'},
        ),
        migrations.AlterField(
            model_name='condition_list',
            name='Condition',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='full_name_of_the_performer_list',
            name='Full_name_of_the_performer',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Full name performer'),
        ),
        migrations.AlterField(
            model_name='historicalcondition_list',
            name='Condition',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='historicalfull_name_of_the_performer_list',
            name='Full_name_of_the_performer',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Full name performer'),
        ),
        migrations.AlterField(
            model_name='historicalrequest',
            name='Comment',
            field=models.TextField(blank=True, max_length=150, verbose_name='Comment from the performer'),
        ),
        migrations.AlterField(
            model_name='historicalrequest',
            name='Condition',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='request.condition_list', verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='historicalrequest',
            name='Customers_full_name',
            field=models.CharField(max_length=50, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='historicalrequest',
            name='Description',
            field=models.TextField(blank=True, max_length=150, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalrequest',
            name='Files',
            field=models.TextField(blank=True, max_length=100, verbose_name='File upload'),
        ),
        migrations.AlterField(
            model_name='historicalrequest',
            name='Lecture_hall',
            field=models.CharField(max_length=10, verbose_name='Office'),
        ),
        migrations.AlterField(
            model_name='historicalrequest',
            name='Performer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='request.full_name_of_the_performer_list', verbose_name='Executor'),
        ),
        migrations.AlterField(
            model_name='historicalrequest',
            name='Request_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Request date'),
        ),
        migrations.AlterField(
            model_name='historicalrequest',
            name='Work',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='request.type_of_work_list', verbose_name='Type of work'),
        ),
        migrations.AlterField(
            model_name='historicaltype_of_work_list',
            name='Type_of_work',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Type of work'),
        ),
        migrations.AlterField(
            model_name='request',
            name='Comment',
            field=models.TextField(blank=True, max_length=150, verbose_name='Comment from the performer'),
        ),
        migrations.AlterField(
            model_name='request',
            name='Condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='request.condition_list', verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='request',
            name='Customers_full_name',
            field=models.CharField(max_length=50, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='request',
            name='Description',
            field=models.TextField(blank=True, max_length=150, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='request',
            name='Files',
            field=models.FileField(blank=True, upload_to='./static/files/%Y/%m/%d/', verbose_name='File upload'),
        ),
        migrations.AlterField(
            model_name='request',
            name='Lecture_hall',
            field=models.CharField(max_length=10, verbose_name='Office'),
        ),
        migrations.AlterField(
            model_name='request',
            name='Performer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='request.full_name_of_the_performer_list', verbose_name='Executor'),
        ),
        migrations.AlterField(
            model_name='request',
            name='Request_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Request date'),
        ),
        migrations.AlterField(
            model_name='request',
            name='Work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='request.type_of_work_list', verbose_name='Type of work'),
        ),
        migrations.AlterField(
            model_name='type_of_work_list',
            name='Type_of_work',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Type of work'),
        ),
    ]
